### ISSUE TITLE
No log send

### ISSUE THREAD

**Issue by cron992** [dxeglow/44CALIBER-MODIFED#2]
Everything is ready and correct, but there is no log.

**Comment by dxeglow** [comment]
You need to build it in as "Release". Do not forget to install .NET Framework on victims machine. If you testing it on Virtual Machine then make sure your protector (if stealer
is protected) blocks the run. In any case you can use programs like "Process Hacker" for view what happends with process.

**Comment by cron992** [comment]
I tried a VM with .NET installed, what is the minimum .NET version for it to work anyway?

Discord now detects Stealer and bans perma, can you add telegram support to this project?

**Comment by dxeglow** [comment]
> I tried a VM with .NET installed, what is the minimum .NET version for it to work anyway?
> 
> Discord now detects Stealer and bans perma, can you add telegram support to this project?

actually i dont work at this project but you can lookup in the internet about this question or try to skid code from other stealers which have this function (Stormkitty as example). I think it not a hard. Sorry.
